-- MySQL Script generated by MySQL Workbench
-- Fri Sep 3 16:03:46 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema newsdb
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `newsdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `newsdb` ;


-- -----------------------------------------------------
-- Table story
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newsdb`.`story` ;
CREATE TABLE IF NOT EXISTS `newsdb`.`story` (
  `sid` int NOT NULL AUTO_INCREMENT,
  `byauthor` varchar(45) DEFAULT NULL,
  `descendants` bigint DEFAULT NULL,
  `newsid` bigint DEFAULT NULL,
  `score` int DEFAULT NULL,
  `newstime` bigint DEFAULT NULL,
  `newstitle` varchar(255) DEFAULT NULL,
  `newstype` varchar(45) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`sid`)
) ENGINE=InnoDB AUTO_INCREMENT=81 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table kids
-- -----------------------------------------------------

DROP TABLE IF EXISTS `newsdb`.`kids` ;
CREATE TABLE IF NOT EXISTS `newsdb`.`kids` (
  `id` int NOT NULL AUTO_INCREMENT,
  `storyid` int DEFAULT NULL,
  `kidsid` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKcv5bmfj5k0npv762o5gt0lyqm` (`storyid`),
  CONSTRAINT `FKcv5bmfj5k0npv762o5gt0lyqm` FOREIGN KEY (`storyid`) REFERENCES `story` (`sid`)
) ENGINE=InnoDB AUTO_INCREMENT=468 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;